export interface NavItem {
  label: string
  slug: string
}

export interface NavSection {
  title: string
  items: NavItem[]
}

export const navSections: NavSection[] = [
  {
    title: 'Core Concepts',
    items: [
      { label: 'Getting Started', slug: 'getting-started' },
      { label: 'Utility Classes', slug: 'utility-classes' },
      { label: 'Hover & Focus States', slug: 'hover-focus-states' },
      { label: 'Responsive Design', slug: 'responsive-design' },
      { label: 'Dark Mode', slug: 'dark-mode' },
      { label: 'Theme Variables', slug: 'theme-variables' },
      { label: 'Colors', slug: 'colors' },
      { label: 'velora.config.js', slug: 'velora-config' },
    ],
  },
  {
    title: 'Base Styles',
    items: [
      { label: 'Preflight', slug: 'preflight' },
    ],
  },
  {
    title: 'Layout',
    items: [
      { label: 'Aspect Ratio', slug: 'aspect-ratio' },
      { label: 'Columns', slug: 'columns' },
      { label: 'Break After', slug: 'break-after' },
      { label: 'Break Before', slug: 'break-before' },
      { label: 'Break Inside', slug: 'break-inside' },
      { label: 'Box Decoration Break', slug: 'box-decoration-break' },
      { label: 'Box Sizing', slug: 'box-sizing' },
      { label: 'Display', slug: 'display' },
      { label: 'Float', slug: 'float' },
      { label: 'Clear', slug: 'clear' },
      { label: 'Isolation', slug: 'isolation' },
      { label: 'Object Fit', slug: 'object-fit' },
      { label: 'Object Position', slug: 'object-position' },
      { label: 'Overflow', slug: 'overflow' },
      { label: 'Overscroll Behavior', slug: 'overscroll-behavior' },
      { label: 'Position', slug: 'position' },
      { label: 'Top / Right / Bottom / Left', slug: 'top-right-bottom-left' },
      { label: 'Visibility', slug: 'visibility' },
      { label: 'Z-Index', slug: 'z-index' },
    ],
  },
  {
    title: 'Flexbox & Grid',
    items: [
      { label: 'Flex Basis', slug: 'flex-basis' },
      { label: 'Flex Direction', slug: 'flex-direction' },
      { label: 'Flex Wrap', slug: 'flex-wrap' },
      { label: 'Flex', slug: 'flex' },
      { label: 'Flex Grow', slug: 'flex-grow' },
      { label: 'Flex Shrink', slug: 'flex-shrink' },
      { label: 'Order', slug: 'order' },
      { label: 'Grid Template Columns', slug: 'grid-template-columns' },
      { label: 'Grid Column', slug: 'grid-column' },
      { label: 'Grid Template Rows', slug: 'grid-template-rows' },
      { label: 'Grid Row', slug: 'grid-row' },
      { label: 'Grid Auto Flow', slug: 'grid-auto-flow' },
      { label: 'Grid Auto Columns', slug: 'grid-auto-columns' },
      { label: 'Grid Auto Rows', slug: 'grid-auto-rows' },
      { label: 'Gap', slug: 'gap' },
      { label: 'Justify Content', slug: 'justify-content' },
      { label: 'Justify Items', slug: 'justify-items' },
      { label: 'Justify Self', slug: 'justify-self' },
      { label: 'Align Content', slug: 'align-content' },
      { label: 'Align Items', slug: 'align-items' },
      { label: 'Align Self', slug: 'align-self' },
      { label: 'Place Content', slug: 'place-content' },
      { label: 'Place Items', slug: 'place-items' },
      { label: 'Place Self', slug: 'place-self' },
    ],
  },
  {
    title: 'Spacing',
    items: [
      { label: 'Padding', slug: 'padding' },
      { label: 'Margin', slug: 'margin' },
    ],
  },
  {
    title: 'Sizing',
    items: [
      { label: 'Width', slug: 'width' },
      { label: 'Min-Width', slug: 'min-width' },
      { label: 'Max-Width', slug: 'max-width' },
      { label: 'Height', slug: 'height' },
      { label: 'Min-Height', slug: 'min-height' },
      { label: 'Max-Height', slug: 'max-height' },
    ],
  },
  {
    title: 'Typography',
    items: [
      { label: 'Font Family', slug: 'font-family' },
      { label: 'Font Size', slug: 'font-size' },
      { label: 'Font Weight', slug: 'font-weight' },
      { label: 'Font Style', slug: 'font-style' },
      { label: 'Letter Spacing', slug: 'letter-spacing' },
      { label: 'Line Height', slug: 'line-height' },
      { label: 'Text Align', slug: 'text-align' },
      { label: 'Text Color', slug: 'text-color' },
      { label: 'Text Decoration', slug: 'text-decoration' },
      { label: 'Text Transform', slug: 'text-transform' },
      { label: 'Text Overflow', slug: 'text-overflow' },
      { label: 'Whitespace', slug: 'whitespace' },
      { label: 'Word Break', slug: 'word-break' },
      { label: 'Vertical Align', slug: 'vertical-align' },
    ],
  },
  {
    title: 'Backgrounds',
    items: [
      { label: 'Background Color', slug: 'background-color' },
      { label: 'Background Position', slug: 'background-position' },
      { label: 'Background Size', slug: 'background-size' },
      { label: 'Background Repeat', slug: 'background-repeat' },
      { label: 'Background Attachment', slug: 'background-attachment' },
      { label: 'Gradient', slug: 'gradient' },
    ],
  },
  {
    title: 'Borders',
    items: [
      { label: 'Border Radius', slug: 'border-radius' },
      { label: 'Border Width', slug: 'border-width' },
      { label: 'Border Color', slug: 'border-color' },
      { label: 'Border Style', slug: 'border-style' },
      { label: 'Outline', slug: 'outline' },
      { label: 'Divide', slug: 'divide' },
      { label: 'Ring', slug: 'ring' },
    ],
  },
  {
    title: 'Effects',
    items: [
      { label: 'Box Shadow', slug: 'box-shadow' },
      { label: 'Opacity', slug: 'opacity' },
      { label: 'Mix Blend Mode', slug: 'mix-blend-mode' },
      { label: 'Blur', slug: 'blur' },
      { label: 'Brightness', slug: 'brightness' },
      { label: 'Grayscale', slug: 'grayscale' },
      { label: 'Backdrop Blur', slug: 'backdrop-blur' },
    ],
  },
  {
    title: 'Animations',
    items: [
      { label: 'Transition', slug: 'transition' },
      { label: 'Animation', slug: 'animation' },
      { label: 'Transform Scale', slug: 'transform-scale' },
      { label: 'Transform Rotate', slug: 'transform-rotate' },
      { label: 'Transform Translate', slug: 'transform-translate' },
    ],
  },
  {
    title: 'Interactivity',
    items: [
      { label: 'Cursor', slug: 'cursor' },
      { label: 'Pointer Events', slug: 'pointer-events' },
      { label: 'User Select', slug: 'user-select' },
      { label: 'Resize', slug: 'resize' },
      { label: 'Scroll Snap', slug: 'scroll-snap' },
      { label: 'Touch Action', slug: 'touch-action' },
    ],
  },
  {
    title: 'Components',
    items: [
      { label: 'Buttons', slug: 'buttons' },
      { label: 'Cards', slug: 'cards' },
      { label: 'Badges', slug: 'badges' },
      { label: 'Alerts', slug: 'alerts' },
      { label: 'Forms', slug: 'forms' },
      { label: 'Navbar', slug: 'navbar' },
      { label: 'Progress', slug: 'progress' },
      { label: 'Spinner', slug: 'spinner' },
      { label: 'Tables', slug: 'tables' },
      { label: 'Tabs', slug: 'tabs' },
      { label: 'Avatar', slug: 'avatar' },
      { label: 'Tooltip', slug: 'tooltip' },
      { label: 'Modal', slug: 'modal' },
      { label: 'Dropdown', slug: 'dropdown' },
      { label: 'Pagination', slug: 'pagination' },
      { label: 'Toast', slug: 'toast' },
      { label: 'Skeleton', slug: 'skeleton' },
      { label: 'Breadcrumb', slug: 'breadcrumb' },
      { label: 'Menu', slug: 'menu' },
      { label: 'Steps', slug: 'steps' },
      { label: 'Divider', slug: 'divider' },
      { label: 'Kbd', slug: 'kbd' },
      { label: 'Accordion', slug: 'accordion' },
      { label: 'Code Block', slug: 'code-block' },
      { label: 'Chat Bubble', slug: 'chat-bubble' },
      { label: 'File Upload', slug: 'file-upload' },
    ],
  },
  {
    title: 'Blocks',
    items: [
      { label: 'Hero', slug: 'hero' },
      { label: 'Feature List', slug: 'feature-list' },
      { label: 'Pricing', slug: 'pricing' },
    ],
  },
  {
    title: 'Innovations',
    items: [
      { label: 'Color Genetics', slug: 'color-genetics' },
      { label: 'Container Queries', slug: 'container-queries' },
      { label: 'CSS State Machine', slug: 'css-state-machine' },
      { label: 'Scope Theming', slug: 'scope-theming' },
      { label: 'Smart Forms', slug: 'smart-forms' },
      { label: 'Fluid Scale', slug: 'fluid-scale' },
    ],
  },
]
